Update bitrise.yml

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -16,6 +16,34 @@ workflows:
         - clone_depth: '1'
     - cocoapods-install@1.6.1: {}
     - script@1.1.3:
+        title: Clone font-image-service
+        inputs:
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            cd ..
+            mkdir font-image-service
+            cd font-image-service
+            git init
+            git remote add -t CI -f origin "$FONT_IMAGE_SERVICE_REPO"
+            git checkout CI
+    - script@1.1.3:
+        title: Add resources
+        inputs:
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            cd $BITRISE_SOURCE_DIR
+            scripts/add-resources.sh
+    - script@1.1.3:
         title: Run headlessly
         inputs:
         - content: |-
@@ -42,6 +70,7 @@ workflows:
 
             cd $documentsPath
             ls
+            ls Images
     before_run: 
     after_run: 
 app:
